plugins { id 'com.android.application' }
android {
    namespace 'ru.avrescue.app'
    compileSdk 36
    defaultConfig {
        applicationId 'ru.avrescue.app'
        minSdk 26
        targetSdk 36
        versionCode 27
        versionName '2.1.6'
    }
}
dependencies {
    implementation 'androidx.core:core:1.15.0'
}
