<?php
require_once __DIR__.'/config.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
av_require_staff_page();
if(!av_staff_can_admin()){http_response_code(403);exit('Доступ только для администратора AV Rescue');}

$id=trim((string)($_GET['id']??$_POST['id']??''));$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!av_check_csrf($_POST['csrf']??''))$err='Сессия устарела. Обновите страницу.';
 else{
  $action=(string)($_POST['action']??'');$reason=trim((string)($_POST['reason']??''));$workers=av_read_workers();$found=false;$staff=av_staff_user();$now=date('c');
  foreach($workers as &$worker)if((string)($worker['id']??'')===$id){
   if($action==='approve'&&!av_verification_complete($worker))$err='Нельзя одобрить водителя: телефон и почта ещё не подтверждены.';
   elseif($action==='approve'){$worker['approved']=true;$worker['review_status']='approved';$worker['approved_at']=$now;$worker['approved_by']=$staff['id']??'';$worker['status']='offline';unset($worker['rejection_reason'],$worker['rejected_at'],$worker['rejected_by']);$msg='Регистрация исполнителя подтверждена.';}
   elseif($action==='reject'&&mb_strlen($reason)>=5){$worker['approved']=false;$worker['review_status']='rejected';$worker['rejection_reason']=$reason;$worker['rejected_at']=$now;$worker['rejected_by']=$staff['id']??'';$worker['status']='offline';$msg='Регистрация отклонена. Причина показана исполнителю.';}
   elseif($action==='reject')$err='Укажите понятную причину — минимум 5 символов.';
   $found=true;break;
  }unset($worker);
  if(!$found)$err='Исполнитель не найден.';
  elseif(!$err&&!av_write_workers($workers))$err='Не удалось сохранить решение.';
  elseif(!$err){$apps=av_executor_apps();foreach($apps as &$app)if((string)($app['id']??'')===$id){$app['status']=$action==='approve'?'approved':'rejected';$app[$action==='approve'?'approved_at':'rejected_at']=$now;if($action==='reject')$app['rejection_reason']=$reason;}unset($app);av_write_executor_apps($apps);av_audit($action==='approve'?'executor_approved':'executor_rejected',$id);}
 }
}
$profile=null;foreach(av_read_workers() as $worker)if((string)($worker['id']??'')===$id){$profile=$worker;break;}
if(!$profile){http_response_code(404);exit('Исполнитель не найден');}
$labels=array('profile_photo'=>'Фото водителя / селфи','vehicle_front'=>'Авто — спереди','vehicle_rear'=>'Авто — сзади','vehicle_left'=>'Авто — левый борт','vehicle_right'=>'Авто — правый борт','driver_license_front'=>'Водительское — лицевая сторона','driver_license_back'=>'Водительское — оборот','sts_front'=>'СТС — лицевая сторона','sts_back'=>'СТС — оборот');
?><!doctype html><html data-av-auth-page="1" lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Исполнитель — AV Rescue</title><style>
:root{--r:#ed111c;--bg:#070809;--p:#111317;--l:#30343a;--m:#aaa}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#fff;font-family:Arial}.w{width:min(1100px,calc(100% - 28px));margin:auto}a{color:inherit;text-decoration:none}.top{display:flex;justify-content:space-between;align-items:center;padding:18px 0;border-bottom:1px solid #292c30}.brand{font-size:25px;font-weight:900}.brand b{color:var(--r)}.btn,button{display:inline-block;background:#17191c;color:#fff;border:1px solid #3a3d42;border-radius:8px;padding:10px 14px;cursor:pointer}.red{background:var(--r);border-color:var(--r)}.green{background:#15803d;border-color:#15803d}.card{background:var(--p);border:1px solid var(--l);border-radius:11px;padding:18px;margin:16px 0}.line{line-height:1.6}.muted{color:var(--m)}.ok{color:#62e594}.err{color:#ff7676}.docs{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.doc{background:#0b0d0f;border:1px solid #30343a;border-radius:9px;padding:9px}.doc img,.missing{display:block;width:100%;height:220px;object-fit:cover;border-radius:7px;background:#070809}.missing{display:grid;place-items:center;color:#777;border:1px dashed #444}.doc b{display:block;margin-top:8px;font-size:13px}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions form{flex:1;min-width:280px}textarea{width:100%;min-height:95px;background:#090b0d;color:#fff;border:1px solid #444;border-radius:8px;padding:10px;margin:8px 0}@media(max-width:800px){.docs{grid-template-columns:1fr 1fr}}@media(max-width:520px){.docs{grid-template-columns:1fr}.top{align-items:flex-start;gap:12px}.doc img,.missing{height:260px}}
</style></head><body><div class="w"><div class="top"><div class="brand">AV<b>R</b> Проверка исполнителя</div><a class="btn" href="/admin.php">Назад в управление</a></div>
<?php if($msg):?><p class="ok"><?php echo htmlspecialchars($msg);?></p><?php endif;?><?php if($err):?><p class="err"><?php echo htmlspecialchars($err);?></p><?php endif;?>
<section class="card"><h1><?php echo htmlspecialchars($profile['name']??'Исполнитель');?></h1><div class="line"><b>ID:</b> <?php echo htmlspecialchars($profile['id']??'');?> · <b>Статус:</b> <?php echo !empty($profile['approved'])?'Подтверждён':'Ожидает проверки';?><br><b>Контакты:</b> <?php echo av_verification_complete($profile)?'телефон и почта подтверждены':'ожидают подтверждения';?><br><b>Телефон:</b> <?php echo htmlspecialchars($profile['phone']??'');?> · <b>Email:</b> <?php echo htmlspecialchars($profile['email']??'');?><br><b>Техника:</b> <?php echo htmlspecialchars($profile['vehicle_type']??'');?> · <b>Госномер:</b> <?php echo htmlspecialchars($profile['plate']??'');?><br><b>Услуги:</b> <?php echo htmlspecialchars(implode(', ',is_array($profile['services']??null)?$profile['services']:array()));?></div><?php if(!empty($profile['rejection_reason'])):?><p class="err"><b>Причина последнего отклонения:</b> <?php echo htmlspecialchars($profile['rejection_reason']);?></p><?php endif;?></section>
<section class="card"><h2>Документы и фотографии</h2><div class="docs"><?php foreach($labels as $kind=>$label):$has=!empty($profile['documents'][$kind]);?><div class="doc"><?php if($has):?><a target="_blank" href="/api/worker_document.php?worker_id=<?php echo urlencode($id);?>&kind=<?php echo urlencode($kind);?>"><img loading="lazy" src="/api/worker_document.php?worker_id=<?php echo urlencode($id);?>&kind=<?php echo urlencode($kind);?>" alt="<?php echo htmlspecialchars($label);?>"></a><?php else:?><div class="missing">Файл не загружен</div><?php endif;?><b><?php echo htmlspecialchars($label);?></b></div><?php endforeach;?></div></section>
<section class="card"><h2>Решение администратора</h2><div class="actions"><form method="post" onsubmit="return confirm('Подтвердить регистрацию исполнителя?');"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="action" value="approve"><button class="green">Подтвердить регистрацию</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="action" value="reject"><textarea name="reason" maxlength="1000" placeholder="Что необходимо исправить? Минимум 5 символов"></textarea><button class="red">Отклонить с причиной</button></form></div></section>
</div></body></html>
