<?php
require_once __DIR__.'/config.php';
$type=trim((string)($_GET['type']??$_POST['type']??''));$id=trim((string)($_GET['id']??$_POST['id']??''));$token=trim((string)($_GET['token']??$_POST['token']??''));$msg='';$err='';
if(!av_verification_authorized($type,$id,$token)){$err='Ссылка подтверждения недействительна.';$record=null;}else{$record=av_verification_record($type,$id);}
if($record&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!av_check_csrf($_POST['csrf']??''))$err='Сессия устарела. Обновите страницу.';
 else{$action=trim((string)($_POST['action']??''));$channel=trim((string)($_POST['channel']??''));
  if($action==='send'){$result=av_verification_send($type,$id,$token,$channel);if(!empty($result['ok']))$msg='Код отправлен на '.($result['masked']??'указанный контакт').'.';else$err=$result['error']??'Не удалось отправить код.';}
  elseif($action==='confirm'){$result=av_verification_confirm($type,$id,$token,$channel,trim((string)($_POST['code']??'')));if(!empty($result['ok']))$msg=!empty($result['complete'])?'Телефон и почта подтверждены. Теперь можно войти.':'Телефон подтверждён. Теперь подтвердите почту.';else$err=$result['error']??'Не удалось подтвердить код.';}
  $record=av_verification_record($type,$id);
 }
}
$complete=$record&&av_verification_complete($record);$phoneDone=$record&&!empty($record['phone_verified_at']);$emailDone=$record&&!empty($record['email_verified_at']);
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08090a"><title>Подтверждение — AV Rescue</title><style>
:root{--r:#ed111c;--bg:#070809;--p:#111317;--l:#30343a;--m:#aeb0b4;--g:#62e594}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#fff;font-family:Arial}.w{width:min(620px,calc(100% - 28px));margin:32px auto}.brand{font-size:28px;font-weight:900;margin-bottom:28px}.brand b{color:var(--r)}.card{background:var(--p);border:1px solid var(--l);border-radius:12px;padding:24px}.step{border-top:1px solid #2b2e33;padding:18px 0}.muted{color:var(--m);line-height:1.5}.ok{color:var(--g)}.err{color:#ff7676}input{width:100%;padding:13px;margin:8px 0;background:#0b0d0f;border:1px solid #34373b;border-radius:7px;color:#fff;font:inherit}button,.btn{display:inline-flex;justify-content:center;padding:12px 16px;border:1px solid var(--r);border-radius:7px;background:var(--r);color:#fff;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#17191c;border-color:#3a3d42}.done{color:var(--g);font-weight:800}form{margin:8px 0}</style></head><body><div class="w"><div class="brand">AV<b>R</b> Rescue</div><div class="card"><h1>Подтвердите контакты</h1><p class="muted">Это защищает аккаунт и помогает восстановить доступ.</p>
<?php if($msg):?><p class="ok"><?php echo htmlspecialchars($msg);?></p><?php endif;?><?php if($err):?><p class="err"><?php echo htmlspecialchars($err);?></p><?php endif;?>
<?php if($record&&!$complete):?><div class="step"><h2>1. Телефон <?php if($phoneDone):?><span class="done">✓</span><?php endif;?></h2><p class="muted"><?php echo htmlspecialchars(av_verification_mask($record['phone']??'','phone'));?></p><?php if(!$phoneDone):?><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="type" value="<?php echo htmlspecialchars($type);?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="token" value="<?php echo htmlspecialchars($token);?>"><input type="hidden" name="action" value="send"><input type="hidden" name="channel" value="phone"><button class="secondary">Получить код по SMS</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="type" value="<?php echo htmlspecialchars($type);?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="token" value="<?php echo htmlspecialchars($token);?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="channel" value="phone"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="6 цифр из SMS" required><button>Подтвердить телефон</button></form><?php endif;?></div>
<div class="step"><h2>2. Почта <?php if($emailDone):?><span class="done">✓</span><?php endif;?></h2><p class="muted"><?php echo htmlspecialchars(av_verification_mask($record['email']??'','email'));?></p><?php if($phoneDone&&!$emailDone):?><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="type" value="<?php echo htmlspecialchars($type);?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="token" value="<?php echo htmlspecialchars($token);?>"><input type="hidden" name="action" value="send"><input type="hidden" name="channel" value="email"><button class="secondary">Получить код на почту</button></form><form method="post"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars(av_csrf());?>"><input type="hidden" name="type" value="<?php echo htmlspecialchars($type);?>"><input type="hidden" name="id" value="<?php echo htmlspecialchars($id);?>"><input type="hidden" name="token" value="<?php echo htmlspecialchars($token);?>"><input type="hidden" name="action" value="confirm"><input type="hidden" name="channel" value="email"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="6 цифр из письма" required><button>Подтвердить почту</button></form><?php elseif(!$phoneDone):?><p class="muted">Станет доступно после подтверждения телефона.</p><?php endif;?></div><?php endif;?>
<?php if($complete):?><p class="ok"><b>Телефон и почта подтверждены.</b></p><a class="btn" href="/login.php">Перейти ко входу</a><?php endif;?></div></div></body></html>
