<?php
require_once __DIR__.'/../config.php';
$p=av_mobile_principal();if(!$p)av_json_response(array('ok'=>false,'error'=>'AUTH_REQUIRED'),401);
$type=$p['principal_type']??'user';$pid=(string)($p['principal_id']??$p['user_id']??'');
$in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))$in=$_POST;
$orderId=trim((string)($in['order_id']??''));$action=trim((string)($in['action']??''));if(!$orderId||!$action)av_json_response(array('ok'=>false,'error'=>'INVALID_REQUEST'),422);
$orders=av_read_orders();$oi=null;foreach($orders as $k=>$o)if(($o['id']??'')===$orderId){$oi=$k;break;}if($oi===null)av_json_response(array('ok'=>false,'error'=>'ORDER_NOT_FOUND'),404);
$staffRole='';if($type==='superadmin')$staffRole='superadmin';elseif($type==='staff'){foreach(av_read_staff() as $s)if(($s['id']??'')===$pid){$staffRole=$s['role']??'dispatcher';break;}}elseif($type==='user'){$uu=av_user_by_id($pid);if($uu&&!empty($uu['staff_role'])&&empty($uu['staff_disabled']))$staffRole=$uu['staff_role'];}
$isStaff=in_array($staffRole,array('superadmin','admin','dispatcher','staff'),true);
$w=null;$workers=av_read_workers();$wi=null;$u=null;if($type==='user'){$u=av_user_by_id($pid);if($u)$w=av_worker_by_user_id($u['id']);}elseif($type==='executor'){foreach($workers as $k=>$x)if(($x['id']??'')===$pid){$w=$x;$wi=$k;break;}}if($w&&$wi===null)foreach($workers as $k=>$x)if(($x['id']??'')===($w['id']??'')){$wi=$k;break;}
$isClientOwner=$type==='user'&&$u&&(($orders[$oi]['user_id']??'')===($u['id']??''));
if($action==='client_cancel'){
 if(!$isClientOwner)av_json_response(array('ok'=>false,'error'=>'FORBIDDEN'),403);if(in_array($orders[$oi]['status']??'',array('done','completed','cancelled'),true))av_json_response(array('ok'=>false,'error'=>'ACTION_NOT_ALLOWED'),422);
 $orders[$oi]['status']='cancelled';$orders[$oi]['cancelled_by']='client';$orders[$oi]['cancelled_at']=date('c');if(!empty($orders[$oi]['assigned_worker_id']))foreach($workers as $k=>$x)if(($x['id']??'')===($orders[$oi]['assigned_worker_id']??'')){$workers[$k]['status']='online';}av_write_workers($workers);
} else {
 if(!$isStaff){if(!$w)av_json_response(array('ok'=>false,'error'=>'EXECUTOR_REQUIRED'),403);if(($orders[$oi]['assigned_worker_id']??'')!==($w['id']??''))av_json_response(array('ok'=>false,'error'=>'ORDER_NOT_ASSIGNED'),403);}
 if($action==='accept'&&$w&&($orders[$oi]['status']??'')==='offered'){$orders[$oi]['status']='assigned';$orders[$oi]['worker_accepted_at']=date('c');if($wi!==null)$workers[$wi]['status']='busy';}
 elseif($action==='reject'&&$w&&($orders[$oi]['status']??'')==='offered'){if(!is_array($orders[$oi]['rejected_worker_ids']??null))$orders[$oi]['rejected_worker_ids']=array();if(!in_array($w['id'],$orders[$oi]['rejected_worker_ids'],true))$orders[$oi]['rejected_worker_ids'][]=$w['id'];$orders[$oi]['assigned_worker_id']='';$orders[$oi]['assigned_worker_name']='';$orders[$oi]['status']='searching';if($wi!==null)$workers[$wi]['status']='online';
   $lat=(float)($orders[$oi]['lat']??0);$lng=(float)($orders[$oi]['lng']??0);$best=null;$bestIndex=null;$score=INF;$now=time();foreach($workers as $candidateIndex=>$cand){if(($cand['status']??'')!=='online'||empty($cand['lat'])||empty($cand['lng'])||in_array($cand['id']??'',$orders[$oi]['rejected_worker_ids'],true))continue;if(!empty($cand['last_seen'])&&$now-strtotime($cand['last_seen'])>180)continue;$services=$cand['services']??array();if($services&&!in_array($orders[$oi]['service']??'',$services,true))continue;$d=av_haversine_km($lat,$lng,(float)$cand['lat'],(float)$cand['lng']);$s=$d-(av_worker_rating($cand['id']??'')*.35);if($s<$score){$score=$s;$best=$cand;$bestIndex=$candidateIndex;$best['distance_km']=$d;}}if($best){$orders[$oi]['assigned_worker_id']=$best['id'];$orders[$oi]['assigned_worker_name']=$best['name']??'';$orders[$oi]['worker_rating']=av_worker_rating($best['id']);$orders[$oi]['status']='offered';$orders[$oi]['offer_created_at']=date('c');$orders[$oi]['estimated_arrival_min']=max(3,(int)round(($best['distance_km']/30)*60));$workers[$bestIndex]['status']='reserved';}
 }
 elseif($action==='enroute'&&($orders[$oi]['status']??'')==='assigned'){$orders[$oi]['status']='enroute';$orders[$oi]['enroute_at']=date('c');if($wi!==null)$workers[$wi]['status']='busy';}
 elseif($action==='arrived'&&($orders[$oi]['status']??'')==='enroute'){$orders[$oi]['status']='arrived';$orders[$oi]['arrived_at']=date('c');$orders[$oi]['estimated_arrival_min']=0;if($wi!==null)$workers[$wi]['status']='busy';}
 elseif($action==='loading'&&($orders[$oi]['status']??'')==='arrived'){$photos=$in['photos']??array();if(!is_array($photos)||count($photos)!==4)av_json_response(array('ok'=>false,'error'=>'FOUR_PHOTOS_REQUIRED_BEFORE_LOADING'),422);$requiredSides=array('order_vehicle_front','order_vehicle_rear','order_vehicle_left','order_vehicle_right');$saved=array();foreach($photos as $photo){$side=trim((string)($photo['side']??''));$path=trim((string)($photo['path']??''));if(!$path||!in_array($side,$requiredSides,true))av_json_response(array('ok'=>false,'error'=>'INVALID_LOADING_PHOTOS'),422);$saved[$side]=array('type'=>$side,'path'=>$path,'created_at'=>date('c'));}if(count($saved)!==4)av_json_response(array('ok'=>false,'error'=>'FOUR_PHOTOS_REQUIRED_BEFORE_LOADING'),422);$orders[$oi]['status']='loading';$orders[$oi]['loading_at']=date('c');$orders[$oi]['before_loading_photos']=array_values($saved);$orders[$oi]['photos']=array_merge(is_array($orders[$oi]['photos']??null)?$orders[$oi]['photos']:array(),array_values($saved));if($wi!==null)$workers[$wi]['status']='busy';}
 elseif($action==='in_transit'&&($orders[$oi]['status']??'')==='loading'){$orders[$oi]['status']='in_transit';$orders[$oi]['in_transit_at']=date('c');if($wi!==null)$workers[$wi]['status']='busy';}
 elseif($action==='done'&&($orders[$oi]['status']??'')==='in_transit'){$orders[$oi]['status']='done';$orders[$oi]['completed_at']=date('c');$orders[$oi]['estimated_arrival_min']=0;if($wi!==null)$workers[$wi]['status']='online';if($w)av_post_order_finance($orders[$oi],$w);}
 elseif($isStaff&&in_array($action,array('searching','cancel','reopen'),true)){$oldWorker=$orders[$oi]['assigned_worker_id']??'';if($oldWorker)foreach($workers as $workerIndex=>$worker)if(($worker['id']??'')===$oldWorker&&in_array($worker['status']??'',array('reserved','busy'),true)){$workers[$workerIndex]['status']='online';}$orders[$oi]['assigned_worker_id']='';$orders[$oi]['assigned_worker_name']='';$orders[$oi]['offer_created_at']='';$orders[$oi]['status']=$action==='cancel'?'cancelled':($action==='reopen'?'new':'searching');if($action==='cancel'){$orders[$oi]['cancelled_by']='dispatcher';$orders[$oi]['cancelled_at']=date('c');}}
 else av_json_response(array('ok'=>false,'error'=>'ACTION_NOT_ALLOWED'),422);
}
$orders[$oi]['updated_at']=date('c');if(!av_write_orders($orders))av_json_response(array('ok'=>false,'error'=>'SAVE_FAILED'),500);if($wi!==null||$action==='reject'||$isStaff||$action==='client_cancel')av_write_workers($workers);av_json_response(array('ok'=>true,'status'=>$orders[$oi]['status'],'order'=>$orders[$oi]));
