<?php
require_once __DIR__.'/../config.php';
require_once __DIR__.'/../partner_orders_helpers.php';
$p=av_mobile_principal();if(!$p)av_json_response(array('ok'=>false,'error'=>'AUTH_REQUIRED'),401);
function md_dispatch_orders(){
 $orders=av_read_orders();$workers=av_read_workers();$ordersChanged=false;$workersChanged=false;$now=time();
 foreach($orders as $i=>$o){
  $status=$o['status']??'';
  if($status==='offered'&&!empty($o['assigned_worker_id']))foreach($workers as $wi=>$worker)if(($worker['id']??'')===($o['assigned_worker_id']??'')&&($worker['status']??'')==='online'){$workers[$wi]['status']='reserved';$workersChanged=true;}
  if($status==='searching'&&!empty($o['assigned_worker_id'])&&empty($o['offer_created_at'])){$old=$o['assigned_worker_id'];foreach($workers as $wi=>$worker)if(($worker['id']??'')===$old&&($worker['status']??'')==='reserved'){$workers[$wi]['status']='online';$workersChanged=true;}$orders[$i]['assigned_worker_id']='';$orders[$i]['assigned_worker_name']='';$ordersChanged=true;}
  if($status==='searching'&&!empty($o['assigned_worker_id'])&&!empty($o['offer_created_at'])&&$now-strtotime($o['offer_created_at'])<300){$orders[$i]['status']='offered';$status='offered';$ordersChanged=true;}
  if($status==='offered'&&!empty($o['offer_created_at'])&&$now-strtotime($o['offer_created_at'])>=300){
   $old=$o['assigned_worker_id']??'';
   if(!is_array($orders[$i]['rejected_worker_ids']??null))$orders[$i]['rejected_worker_ids']=array();
   if($old&&!in_array($old,$orders[$i]['rejected_worker_ids'],true))$orders[$i]['rejected_worker_ids'][]=$old;
   foreach($workers as $wi=>$worker)if(($worker['id']??'')===$old&&($worker['status']??'')==='reserved'){$workers[$wi]['status']='online';$workersChanged=true;}
   $orders[$i]['assigned_worker_id']='';$orders[$i]['assigned_worker_name']='';$orders[$i]['offer_created_at']='';$orders[$i]['status']='searching';$status='searching';$ordersChanged=true;
  }
  if($status!=='searching'||!empty($orders[$i]['assigned_worker_id'])||empty($o['lat'])||empty($o['lng']))continue;
  $bestIndex=null;$bestScore=INF;$bestDistance=0;$rejected=$orders[$i]['rejected_worker_ids']??array();
  foreach($workers as $wi=>$candidate){
   if(($candidate['status']??'')!=='online'||empty($candidate['lat'])||empty($candidate['lng'])||in_array($candidate['id']??'',$rejected,true))continue;
   if(empty($candidate['last_seen'])||$now-strtotime($candidate['last_seen'])>180)continue;
   $services=$candidate['services']??array();if($services&&!in_array($o['service']??'',$services,true))continue;
   $distance=av_haversine_km((float)$o['lat'],(float)$o['lng'],(float)$candidate['lat'],(float)$candidate['lng']);
   $candidateScore=$distance-av_worker_rating($candidate['id']??'')*.35;if($candidateScore<$bestScore){$bestScore=$candidateScore;$bestIndex=$wi;$bestDistance=$distance;}
  }
  if($bestIndex!==null){
   $best=$workers[$bestIndex];$orders[$i]['assigned_worker_id']=$best['id'];$orders[$i]['assigned_worker_name']=$best['name']??'';$orders[$i]['worker_rating']=av_worker_rating($best['id']);$orders[$i]['status']='offered';$orders[$i]['offer_created_at']=date('c');$orders[$i]['estimated_arrival_min']=max(1,(int)ceil(($bestDistance/30)*60));$workers[$bestIndex]['status']='reserved';$ordersChanged=true;$workersChanged=true;
  }
 }
 if($ordersChanged)av_write_orders($orders);if($workersChanged)av_write_workers($workers);
}
md_dispatch_orders();
function md_reconcile_finance($workerId){if(!$workerId||!function_exists('av_ledger_add_once'))return;$orders=av_read_orders();$changed=false;$worker=av_worker_by_id($workerId);foreach($orders as $i=>$o){if(($o['assigned_worker_id']??'')!==$workerId||!in_array($o['status']??'',array('done','completed'),true)||!empty($o['finance_posted']))continue;$f=av_order_financials($o,$worker);if(!empty($f['excluded'])){$orders[$i]['finance_posted']='b2b_separate';$orders[$i]['loyalty_level']='b2b';$orders[$i]['loyalty_name']='B2B — отдельный учёт';$changed=true;continue;}av_finance_record_order($o,$f);$cash=($o['payment_method']??'cash')==='cash';$amount=$cash?-$f['commission']:$f['driver_net'];av_ledger_add_once($workerId,$o['id']??'',$cash?'commission_debit':'driver_credit',$amount,$cash?'Комиссия за наличный заказ':'Оплата картой за заказ');$orders[$i]['final_price']=$f['gross'];$orders[$i]['commission_rate']=$f['commission_rate'];$orders[$i]['payout_rate']=$f['payout_rate'];$orders[$i]['commission_amount']=$f['commission'];$orders[$i]['worker_payout']=$f['driver_net'];$orders[$i]['loyalty_level']=$f['loyalty_level'];$orders[$i]['loyalty_name']=$f['loyalty_name'];$orders[$i]['ledger_amount']=$amount;$orders[$i]['finance_posted']=true;$changed=true;}if($changed)av_write_orders($orders);}
$type=$p['principal_type']??'user';$id=(string)($p['principal_id']??$p['user_id']??'');$profile=array('id'=>$id,'name'=>'','phone'=>'','rating'=>5,'role'=>$type);$executor=null;$fleet=null;$orders=array();$finance=null;$partnerOrders=array();$partnerOrderHistory=array();
if($type==='user'){
 $u=av_user_by_id($id);if(!$u)av_json_response(array('ok'=>false,'error'=>'AUTH_REQUIRED'),401);$w=av_worker_by_user_id($u['id']);$staffRole=!empty($u['staff_disabled'])?null:($u['staff_role']??null);
 $activeRole=$p['active_role']??'';
 $effectiveRole=$activeRole==='client'?'client':($activeRole==='staff'&&$staffRole?$staffRole:($activeRole==='executor'&&$w?'executor':($staffRole?:($w?'executor':'client'))));
 $profile=array('id'=>$u['id'],'name'=>$u['name']??'','phone'=>$u['phone']??'','rating'=>av_client_rating($u['id'],$u['phone']??''),'role'=>$effectiveRole);
 if($w&&$effectiveRole==='executor'){if(empty($w['approved'])){$rejected=(($w['review_status']??'')==='rejected');av_json_response(array('ok'=>false,'error'=>$rejected?'Регистрация отклонена: '.($w['rejection_reason']??'Исправьте данные анкеты.'):'Анкета исполнителя ожидает проверки','moderation_status'=>$w['review_status']??'review','rejection_reason'=>$w['rejection_reason']??''),403);}md_reconcile_finance($w['id']);$loyalty=av_worker_loyalty($w);$executor=array_merge($w,array('rating'=>av_worker_rating($w['id']),'balance'=>av_driver_balance($w['id']),'commission_rate'=>$loyalty['commission_rate'],'payout_rate'=>$loyalty['payout_rate'],'loyalty'=>$loyalty));$finance=av_worker_finance_summary($w['id']);$fleet=av_fleet_vehicle_by_driver($u['id']);}
 if(in_array($effectiveRole,array('superadmin','admin','dispatcher','staff'),true)){$orders=av_read_orders();$partnerOrders=av_partner_orders();}else foreach(av_read_orders() as $o)if(($effectiveRole==='executor'&&$w&&($o['assigned_worker_id']??'')===($w['id']??''))||($effectiveRole==='client'&&($o['user_id']??'')===$u['id']))$orders[]=$o;
}elseif($type==='executor'){
 $w=null;foreach(av_read_workers() as $x)if(($x['id']??'')===$id){$w=$x;break;}if(!$w)av_json_response(array('ok'=>false,'error'=>'AUTH_REQUIRED'),401);if(empty($w['approved'])){$rejected=(($w['review_status']??'')==='rejected');av_json_response(array('ok'=>false,'error'=>$rejected?'Регистрация отклонена: '.($w['rejection_reason']??'Исправьте данные анкеты.'):'Анкета исполнителя ожидает проверки','moderation_status'=>$w['review_status']??'review','rejection_reason'=>$w['rejection_reason']??''),403);}md_reconcile_finance($w['id']);$loyalty=av_worker_loyalty($w);$profile=array('id'=>$w['id'],'name'=>$w['name']??'','phone'=>$w['phone']??'','rating'=>av_worker_rating($w['id']),'role'=>'executor');$executor=array_merge($w,array('rating'=>av_worker_rating($w['id']),'balance'=>av_driver_balance($w['id']),'commission_rate'=>$loyalty['commission_rate'],'payout_rate'=>$loyalty['payout_rate'],'loyalty'=>$loyalty));$finance=av_worker_finance_summary($w['id']);foreach(av_read_orders() as $o)if(($o['assigned_worker_id']??'')===$w['id'])$orders[]=$o;
}elseif($type==='b2b'){$b=null;foreach(av_read_b2b() as $x)if(($x['id']??'')===$id){$b=$x;break;}if(!$b)av_json_response(array('ok'=>false,'error'=>'AUTH_REQUIRED'),401);$profile=array('id'=>$b['id'],'name'=>$b['company']??$b['contact']??'B2B','phone'=>$b['phone']??'','rating'=>5,'role'=>'b2b');foreach(av_read_orders() as $o)if(($o['b2b_id']??'')===$b['id'])$orders[]=$o;
}elseif($type==='staff'||$type==='superadmin'){$role=$type==='superadmin'?'superadmin':'dispatcher';$name='Главный администратор';if($type==='staff'){foreach(av_read_staff() as $s)if(($s['id']??'')===$id){$role=$s['role']??'dispatcher';$name=$s['name']??'Сотрудник';break;}}$profile=array('id'=>$id,'name'=>$name,'phone'=>'','rating'=>5,'role'=>$role);$orders=av_read_orders();$partnerOrders=av_partner_orders();}
$stats=array('new'=>0,'active'=>0,'done'=>0,'cancelled'=>0);foreach($orders as $o){$s=$o['status']??'';if($s==='new')$stats['new']++;if(in_array($s,array('new','searching','offered','assigned','enroute','arrived','loading','in_transit'),true))$stats['active']++;if(in_array($s,array('done','completed'),true))$stats['done']++;if($s==='cancelled')$stats['cancelled']++;}
usort($orders,fn($a,$b)=>strcmp($b['created_at']??'',$a['created_at']??''));
foreach($orders as &$mobileOrder){if(($mobileOrder['status']??'')==='offered'){$started=strtotime($mobileOrder['offer_created_at']??'');$mobileOrder['offer_seconds_left']=$started?max(0,300-(time()-$started)):300;}}unset($mobileOrder);
if($executor!==null){if(!is_array($finance))$finance=array();$balance=(float)($executor['balance']??0);$requested=(float)($finance['requested']??0);$finance['current_balance']=$balance;$finance['debt']=max(0,-$balance);$finance['available']=max(0,$balance-$requested);$transactions=array();$grossTotal=0;$commissionTotal=0;$earnedTotal=0;foreach($orders as $o){if(!in_array($o['status']??'',array('done','completed'),true)||!empty($o['b2b_id'])||($o['source']??'')==='max_partner'||($o['finance_posted']??'')==='b2b_separate')continue;$gross=(float)($o['final_price']??$o['estimated_price']??0);$commission=(float)($o['commission_amount']??0);$net=(float)($o['worker_payout']??($gross-$commission));$grossTotal+=$gross;$commissionTotal+=$commission;$earnedTotal+=$net;$cash=($o['payment_method']??'cash')==='cash';$transactions[]=array('order_id'=>$o['id']??'','completed_at'=>$o['completed_at']??$o['updated_at']??'','price'=>$gross,'payment_method'=>$cash?'cash':'online','commission'=>$commission,'driver_net'=>$net,'balance_change'=>(float)($o['ledger_amount']??($cash?-$commission:$net)));}$payoutRows=array();foreach(av_read_payouts() as $payout)if(($payout['worker_id']??'')===($executor['id']??''))$payoutRows[]=$payout;usort($payoutRows,fn($a,$b)=>strcmp($b['created_at']??'',$a['created_at']??''));$finance['gross']=$grossTotal;$finance['commission']=$commissionTotal;$finance['earned']=$earnedTotal;$finance['transactions']=$transactions;$finance['payouts']=array_slice($payoutRows,0,50);$partnerOrders=av_partner_orders_for_worker($executor);$partnerOrderHistory=av_partner_order_history_for_worker($executor);}
av_json_response(array('ok'=>true,'profile'=>$profile,'executor'=>$executor,'finance'=>$finance,'fleet_vehicle'=>$fleet,'orders'=>array_slice($orders,0,100),'partner_orders'=>$partnerOrders,'partner_order_history'=>$partnerOrderHistory,'stats'=>$stats,'capabilities'=>array('tracking'=>true,'order_actions'=>true,'partner_orders'=>true,'partner_order_history'=>true,'payments'=>'prepared','weather'=>'integration_ready','routing'=>'integration_ready','push'=>'integration_ready','glonass'=>'deferred')));
