package ru.avrescue.app;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Bitmap;import android.graphics.BitmapFactory;import android.location.*;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.time.*;
public class DashboardActivity extends Activity implements LocationListener{
 LinearLayout root,content,nav;LocationManager lm;String role="client",notifiedOfferId="";JSONObject data;boolean executor=false,online=false;Location lastLocation;Handler handler=new Handler(Looper.getMainLooper());boolean polling=false,waitingForOnline=false;String currentPage="Главная";TextView offerTimer;long offerDeadlineElapsed=0;
 Runnable poll=new Runnable(){@Override public void run(){if(executor&&!isFinishing()){refreshQuiet();handler.postDelayed(this,10000);}}};
 Runnable offerTicker=new Runnable(){@Override public void run(){if(offerTimer==null||offerDeadlineElapsed<=0||isFinishing())return;String left=offerTimeLeft();offerTimer.setText("На принятие: "+left);if("0:00".equals(left)){refreshQuiet();return;}handler.postDelayed(this,1000);}};
 public void onCreate(Bundle b){super.onCreate(b);ApiClient.load(this);build();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},92);load();}
 protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);load();}
 protected void onResume(){super.onResume();if(executor&&!polling){polling=true;handler.postDelayed(poll,3000);}}
 protected void onPause(){super.onPause();handler.removeCallbacks(poll);handler.removeCallbacks(offerTicker);polling=false;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Ui.BG);ScrollView s=new ScrollView(this);content=Ui.column(this);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setBackgroundColor(Ui.PANEL);root.addView(nav,new LinearLayout.LayoutParams(-1,-2));setContentView(root);}
 void header(){content.addView(Ui.brand(this));content.addView(Ui.chip(this,"● САО • СВАО • ближайшая Московская область",true));}
 void load(){content.removeAllViews();header();content.addView(Ui.muted(this,"Загрузка…",14));new Thread(()->{try{JSONObject r=ApiClient.get("/api/mobile_dashboard.php");runOnUiThread(()->render(r));}catch(Exception e){runOnUiThread(()->error("Нет связи с сервером"));}}).start();}
 void refreshQuiet(){new Thread(()->{try{JSONObject r=ApiClient.get("/api/mobile_dashboard.php");runOnUiThread(()->{if(r.optBoolean("ok")){data=r;JSONObject p=r.optJSONObject("profile");role=p==null?"client":p.optString("role","client");executor="executor".equals(role);JSONObject ex=r.optJSONObject("executor");String executorStatus=ex==null?"":ex.optString("status");online=ex!=null&&("online".equals(executorStatus)||"reserved".equals(executorStatus)||"busy".equals(executorStatus));if(executor&&online)startDriverService();setupNav();if("Главная".equals(currentPage))home();else if("Работа на линии".equals(currentPage))linePage();else if("Заказы".equals(currentPage)||"Заявки и заказы".equals(currentPage))orders();else if("Журнал B2B".equals(currentPage))partnerHistory();else if("Доход и комиссия".equals(currentPage))finance();}});}catch(Exception ignored){}}).start();}
 void error(String s){content.removeAllViews();header();content.addView(Ui.muted(this,s,15));}
 void render(JSONObject r){if(r.optInt("_http")==401){ApiClient.clear(this);startActivity(new Intent(this,LoginActivity.class));finish();return;}if(!r.optBoolean("ok")){error(r.optString("error","Ошибка"));return;}data=r;JSONObject p=r.optJSONObject("profile");role=p==null?"client":p.optString("role","client");executor="executor".equals(role);JSONObject ex=r.optJSONObject("executor");String executorStatus=ex==null?"":ex.optString("status");online=ex!=null&&("online".equals(executorStatus)||"reserved".equals(executorStatus)||"busy".equals(executorStatus));if(executor&&online)startDriverService();setupNav();if(executor&&getIntent().getBooleanExtra("open_line",false)){getIntent().removeExtra("open_line");linePage();}else home();if(executor&&!polling){polling=true;handler.postDelayed(poll,3000);}}
 boolean staff(){return "superadmin".equals(role)||"admin".equals(role)||"dispatcher".equals(role)||"staff".equals(role);}boolean admin(){return "superadmin".equals(role)||"admin".equals(role);}
 void addNav(String t,Runnable r){Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(10);b.setPadding(1,0,1,0);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(v->r.run());nav.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));}
 void setupNav(){nav.removeAllViews();if(staff()){addNav("Главная",()->home());addNav("Заказы",()->orders());addNav("Водители",()->resources("workers","Исполнители"));addNav("Автопарк",()->resources("fleet","Автопарк"));addNav("Ещё",()->more());}else if(executor){addNav("Главная",()->home());addNav("Заказы",()->orders());addNav(online?"На линии":"Не на линии",()->linePage());addNav("Доход",()->finance());addNav("Ещё",()->more());}else{addNav("Главная",()->home());addNav("Заказы",()->orders());addNav("Помощь",()->startActivity(new Intent(this,CreateOrderActivity.class)));addNav("Профиль",()->more());}}
 void page(String t){currentPage=t;handler.removeCallbacks(offerTicker);offerTimer=null;offerDeadlineElapsed=0;content.removeAllViews();header();content.addView(Ui.text(this,t,25,true));}
 void home(){page("Главная");JSONObject p=data.optJSONObject("profile"),ex=data.optJSONObject("executor");LinearLayout c=Ui.card(this);c.addView(Ui.text(this,"Здравствуйте, "+(p==null?"":p.optString("name")),22,true));c.addView(Ui.chip(this,"● "+roleRu(role),true));if(ex!=null){c.addView(Ui.muted(this,"Рейтинг "+ex.optDouble("rating",5)+" • комиссия "+Math.round(ex.optDouble("commission_rate",20))+"%",14));c.addView(Ui.chip(this,online?"● ВЫ НА ЛИНИИ":"● НЕ НА ЛИНИИ",online));}content.addView(c);JSONObject st=data.optJSONObject("stats");if(staff()&&st!=null){LinearLayout s=Ui.card(this);s.addView(Ui.text(this,"Сводка",19,true));s.addView(Ui.text(this,"Новые: "+st.optInt("new")+"   Активные: "+st.optInt("active"),16,true));s.addView(Ui.text(this,"Завершено: "+st.optInt("done")+"   Отменено: "+st.optInt("cancelled"),15,false));content.addView(s);}if(staff()){quick("Заявки и заказы","Диспетчерская",()->orders());quick("Исполнители","Статусы, рейтинг, геопозиция",()->resources("workers","Исполнители"));quick("Заявки на регистрацию","Обязательная проверка анкет и документов",()->applications());}else if(executor){driverOffer();partnerOrdersSection(2);quick("Журнал B2B","Закрытые через MAX поездки, которые выполняли вы",()->partnerHistory());quick("Работа на линии",online?"GPS передаётся • система ищет заказы рядом":"Выйдите на линию, чтобы получать ближайшие заказы",()->linePage());quick("Мои заказы","Предложения и активные заказы",()->orders());quick("Доход и комиссия","Баланс, комиссия AV Rescue и к выплате",()->finance());}else{quick("Вызвать помощь","Рассчитать стоимость и создать заказ",()->startActivity(new Intent(this,CreateOrderActivity.class)));quick("Мои заказы","Отслеживание, стоимость и рейтинг",()->orders());}preview();}
 void driverOffer(){JSONArray a=data.optJSONArray("orders");if(a==null)return;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&"offered".equals(o.optString("status"))){String id=o.optString("id");notifiedOfferId=id;LinearLayout c=Ui.card(this);c.addView(Ui.text(this,"НОВЫЙ ЗАКАЗ",21,true));c.addView(Ui.text(this,o.optString("service","Услуга"),18,true));c.addView(Ui.muted(this,"Подача: "+o.optString("address","Не указана"),14));c.addView(Ui.muted(this,"Назначение: "+o.optString("destination","Не указано"),14));double price=o.optDouble("estimated_price",0);double rate=data.optJSONObject("executor")==null?20:data.optJSONObject("executor").optDouble("commission_rate",20);if(price>0){c.addView(Ui.text(this,Math.round(price)+" ₽",22,true));c.addView(Ui.muted(this,"Комиссия "+Math.round(rate)+"% • вам ≈ "+Math.round(price*(1-rate/100.0))+" ₽",14));}int eta=o.optInt("estimated_arrival_min",0);if(eta>0)c.addView(Ui.chip(this,"До клиента ≈ "+eta+" мин",true));int seconds=Math.max(0,Math.min(300,o.optInt("offer_seconds_left",300)));offerDeadlineElapsed=SystemClock.elapsedRealtime()+seconds*1000L;offerTimer=Ui.chip(this,"На принятие: "+offerTimeLeft(),true);c.addView(offerTimer);Button accept=Ui.button(this,"Принять заказ");accept.setOnClickListener(v->acceptAndOpen(id,accept));c.addView(accept);content.addView(c);handler.removeCallbacks(offerTicker);handler.post(offerTicker);break;}}}
 String offerTimeLeft(){long millis=Math.max(0,offerDeadlineElapsed-SystemClock.elapsedRealtime());long left=(millis+999)/1000;return String.format(java.util.Locale.US,"%d:%02d",left/60,left%60);}
 void acceptAndOpen(String id,Button button){stopOfferAlert();button.setEnabled(false);button.setText("Принимаем заказ…");new Thread(()->{try{JSONObject r=ApiClient.post("/api/mobile_order_action.php",new JSONObject().put("order_id",id).put("action","accept"));runOnUiThread(()->{if(r.optBoolean("ok")&&"assigned".equals(r.optString("status"))){handler.removeCallbacks(offerTicker);openOrder(id);}else{button.setEnabled(true);button.setText("Принять заказ");Toast.makeText(this,r.optString("error","Заказ уже недоступен"),Toast.LENGTH_LONG).show();refreshQuiet();}});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);button.setText("Принять заказ");Toast.makeText(this,"Нет связи с AV Rescue",Toast.LENGTH_LONG).show();});}}).start();}
 void quick(String t,String d,Runnable r){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,t,18,true));c.addView(Ui.muted(this,d,13));c.setOnClickListener(v->r.run());content.addView(c);}
 void preview(){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,staff()?"Последние заказы":"Мои заказы",19,true));JSONArray a=data.optJSONArray("orders");if(a==null||a.length()==0)c.addView(Ui.muted(this,"Заказов пока нет.",14));else for(int i=0;i<Math.min(3,a.length());i++)order(c,a.optJSONObject(i));content.addView(c);}
 void orders(){page(staff()?"Заявки и заказы":"Заказы");if(executor){partnerOrdersSection(0);Button history=Ui.darkButton(this,"Открыть журнал B2B");history.setOnClickListener(v->partnerHistory());content.addView(history);}JSONArray a=data.optJSONArray("orders");if(executor)content.addView(Ui.text(this,"Заказы AV Rescue",19,true));if(a==null||a.length()==0)content.addView(Ui.muted(this,"Заказов AV Rescue пока нет.",14));else for(int i=0;i<a.length();i++){LinearLayout c=Ui.card(this);order(c,a.optJSONObject(i));content.addView(c);}Button b=Ui.darkButton(this,"Обновить");b.setOnClickListener(v->refreshQuiet());content.addView(b);}
 void order(LinearLayout p,JSONObject o){if(o==null)return;p.addView(Ui.text(this,o.optString("id")+" • "+o.optString("service"),15,true));p.addView(Ui.muted(this,statusRu(o.optString("status"))+" • "+o.optString("address"),13));double price=o.optDouble("final_price",o.optDouble("estimated_price",0));if(price>0)p.addView(Ui.text(this,Math.round(price)+" ₽",16,true));String id=o.optString("id");p.setOnClickListener(v->openOrder(id));}
 void openOrder(String id){Intent in=new Intent(this,OrderDetailActivity.class);in.putExtra("order_id",id);in.putExtra("role",role);startActivity(in);}
 void partnerOrdersSection(int limit){
  JSONArray rows=data.optJSONArray("partner_orders");
  if(rows==null||rows.length()==0)return;
  content.addView(Ui.text(this,"Заявки партнёра",19,true));
  content.addView(Ui.muted(this,"Без стоимости и комиссии AV Rescue",13));
  int count=limit>0?Math.min(limit,rows.length()):rows.length();
  for(int i=0;i<count;i++){JSONObject order=rows.optJSONObject(i);if(order!=null)content.addView(partnerOrderCard(order));}
  if(limit>0&&rows.length()>limit){Button all=Ui.darkButton(this,"Показать все заявки партнёра");all.setOnClickListener(v->orders());content.addView(all);}
 }
 LinearLayout partnerOrderCard(JSONObject order){
  LinearLayout card=Ui.card(this);boolean mine=order.optBoolean("is_mine");String status=order.optString("status","available");boolean atPickup=mine&&"at_pickup".equals(order.optString("driver_stage","to_pickup"));
  String title=order.optString("service","Эвакуация");String vehicle=order.optString("vehicle","");String plate=order.optString("license_plate","");
  card.addView(Ui.text(this,title,18,true));
  String statusText=mine?"● ВЫ ВЗЯЛИ ЗАЯВКУ":"claimed".equals(status)?"● Взял: "+order.optString("assigned_worker_name","водитель"):"● СВОБОДНА";
  card.addView(Ui.chip(this,statusText,mine||"available".equals(status)));
  card.addView(Ui.muted(this,"Подача: "+valueOr(order.optString("pickup_address",""),"Координаты на карте"),14));
  if(!order.isNull("distance_km")){card.addView(Ui.chip(this,order.optDouble("distance_km")+" км • примерно "+order.optInt("eta_min")+" мин",true));}
  double lat=order.optDouble("pickup_lat",0),lng=order.optDouble("pickup_lng",0);String address=order.optString("pickup_address","");
  if((lat!=0&&lng!=0)||!address.isEmpty()){Button map=Ui.darkButton(this,"Маршрут к подаче");map.setOnClickListener(v->openYandexMap(lat,lng,address));card.addView(map);}
  LinearLayout details=new LinearLayout(this);details.setOrientation(LinearLayout.VERTICAL);details.setVisibility(mine?android.view.View.VISIBLE:android.view.View.GONE);
  if(!vehicle.isEmpty())details.addView(Ui.muted(this,"Автомобиль: "+vehicle,14));if(!plate.isEmpty())details.addView(Ui.muted(this,"Госномер: "+plate,14));
  String until=order.optString("service_until","");if(!until.isEmpty())details.addView(Ui.muted(this,"Время работы сервиса: "+until,13));
  String phone=order.optString("phone","");if(!phone.isEmpty()){Button call=Ui.darkButton(this,"Позвонить: "+phone);call.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(phone)))));details.addView(call);}
  String comment=order.optString("comment","");if(!comment.isEmpty())details.addView(Ui.muted(this,"Комментарий: "+comment,13));
  double destinationLat=order.optDouble("destination_lat",0),destinationLng=order.optDouble("destination_lng",0);String destination=order.optString("destination","");
  if(atPickup){details.addView(Ui.text(this,"Точка Б: "+valueOr(destination,"Не указано"),16,true));if((destinationLat!=0&&destinationLng!=0)||!destination.isEmpty()){Button map=Ui.button(this,"Маршрут к точке Б");map.setOnClickListener(v->openYandexMap(destinationLat,destinationLng,destination));details.addView(map);}}else if(mine)details.addView(Ui.muted(this,"Точка Б появится после нажатия «На месте».",14));
  if(!mine){Button show=Ui.darkButton(this,"Открыть заявку");show.setOnClickListener(v->{boolean opening=details.getVisibility()!=android.view.View.VISIBLE;details.setVisibility(opening?android.view.View.VISIBLE:android.view.View.GONE);show.setText(opening?"Скрыть детали":"Открыть заявку");});card.addView(show);}card.addView(details);
  String id=order.optString("id","");
  if(mine&&!atPickup){Button arrived=Ui.button(this,"На месте — открыть точку Б");arrived.setOnClickListener(v->partnerAction(id,"arrive",arrived));card.addView(arrived);Button release=Ui.darkButton(this,"Вернуть в общий список");release.setOnClickListener(v->partnerAction(id,"release",release));card.addView(release);}
  else if("available".equals(status)){Button claim=Ui.button(this,"Взять в работу");claim.setOnClickListener(v->partnerAction(id,"claim",claim));card.addView(claim);}
  return card;
 }
 String valueOr(String value,String fallback){return value==null||value.trim().isEmpty()?fallback:value;}
 void partnerAction(String id,String action,Button button){
  button.setEnabled(false);button.setText("claim".equals(action)?"Принимаем…":"arrive".equals(action)?"Отмечаем прибытие…":"Возвращаем…");
  new Thread(()->{try{JSONObject r=ApiClient.post("/api/partner_order_action.php",new JSONObject().put("order_id",id).put("action",action));runOnUiThread(()->{if(r.optBoolean("ok")){Toast.makeText(this,"claim".equals(action)?"Заявка закреплена за вами":"arrive".equals(action)?"Точка Б открыта":"Заявка возвращена в список",Toast.LENGTH_LONG).show();refreshQuiet();}else{button.setEnabled(true);button.setText("claim".equals(action)?"Взять в работу":"arrive".equals(action)?"На месте — открыть точку Б":"Вернуть в общий список");Toast.makeText(this,partnerError(r.optString("error")),Toast.LENGTH_LONG).show();}});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);Toast.makeText(this,"Нет связи с AV Rescue",Toast.LENGTH_LONG).show();});}}).start();
 }
 void partnerHistory(){page("Журнал B2B");JSONArray rows=data.optJSONArray("partner_order_history");if(rows==null||rows.length()==0){content.addView(Ui.muted(this,"Закрытых B2B-поездок пока нет.",14));return;}for(int i=0;i<rows.length();i++){JSONObject order=rows.optJSONObject(i);if(order==null)continue;LinearLayout card=Ui.card(this);card.addView(Ui.text(this,order.optString("service","Эвакуация")+" • "+valueOr(order.optString("license_plate",""),order.optString("id","")),17,true));card.addView(Ui.chip(this,"● ЗАКРЫТА ЧЕРЕЗ MAX",true));card.addView(Ui.muted(this,"Точка А: "+valueOr(order.optString("pickup_address",""),"Не указана"),14));card.addView(Ui.muted(this,"Точка Б: "+valueOr(order.optString("destination",""),"Не указана"),14));String vehicle=order.optString("vehicle","");if(!vehicle.isEmpty())card.addView(Ui.muted(this,"Автомобиль: "+vehicle,14));String comment=order.optString("comment","");if(!comment.isEmpty())card.addView(Ui.muted(this,"Комментарий: "+comment,13));String closed=order.optString("closed_at",order.optString("updated_at",""));if(!closed.isEmpty())card.addView(Ui.muted(this,"Закрыта: "+closed,12));content.addView(card);}Button refresh=Ui.darkButton(this,"Обновить журнал");refresh.setOnClickListener(v->refreshQuiet());content.addView(refresh);}
 String partnerError(String error){if("ALREADY_CLAIMED".equals(error))return "Эту заявку уже взял другой водитель";if("GO_ONLINE_FIRST".equals(error))return "Сначала выйдите на линию";if("ORDER_CLOSED".equals(error))return "Заявка уже закрыта";if("OWN_FLEET_ONLY".equals(error))return "Заявка доступна только собственному парку";return error==null||error.isEmpty()?"Не удалось обновить заявку":error;}
 void openYandexMap(double lat,double lng,String address){
  Uri uri=(lat!=0&&lng!=0)?Uri.parse("yandexnavi://build_route_on_map?lat_to="+lat+"&lon_to="+lng):Uri.parse("https://yandex.ru/maps/?text="+Uri.encode(address));
  Intent intent=new Intent(Intent.ACTION_VIEW,uri);intent.setPackage("ru.yandex.yandexnavi");
  try{startActivity(intent);}catch(Exception e){Uri web=(lat!=0&&lng!=0)?Uri.parse("https://yandex.ru/maps/?ll="+lng+"%2C"+lat+"&z=16&pt="+lng+"%2C"+lat+"%2Cpm2rdm"):Uri.parse("https://yandex.ru/maps/?text="+Uri.encode(address));try{startActivity(new Intent(Intent.ACTION_VIEW,web));}catch(Exception ignored){Toast.makeText(this,"Не удалось открыть Яндекс Карты",Toast.LENGTH_SHORT).show();}}
 }
 void linePage(){page("Работа на линии");LinearLayout c=Ui.card(this);c.addView(Ui.chip(this,online?"● ВЫ НА ЛИНИИ":"● НЕ НА ЛИНИИ",online));c.addView(Ui.muted(this,online?"AV Rescue получает вашу геопозицию и может предлагать ближайшие заказы.":"В офлайн-режиме новые заказы не назначаются.",14));Button toggle=Ui.button(this,online?"Уйти с линии":"Выйти на линию");toggle.setOnClickListener(v->{if(online)goOffline();else startLocationUpdates();});c.addView(toggle);Button refresh=Ui.darkButton(this,"Обновить заказы");refresh.setOnClickListener(v->refreshQuiet());c.addView(refresh);content.addView(c);driverOffer();partnerOrdersSection(0);}
 void startLocationUpdates(){lm=(LocationManager)getSystemService(LOCATION_SERVICE);if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION,android.Manifest.permission.ACCESS_COARSE_LOCATION},90);return;}waitingForOnline=true;Toast.makeText(this,"Получаем GPS…",Toast.LENGTH_SHORT).show();try{if(lm.isProviderEnabled(LocationManager.GPS_PROVIDER))lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,15000,20,this);if(lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER))lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,15000,20,this);Location x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(x==null)x=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(x!=null){waitingForOnline=false;sendLocation(x,true);}}catch(Exception e){Toast.makeText(this,"Включите геолокацию",Toast.LENGTH_LONG).show();}}
 void startDriverService(){Intent service=new Intent(this,DriverLocationService.class).setAction(DriverLocationService.ACTION_START);if(Build.VERSION.SDK_INT>=26)startForegroundService(service);else startService(service);}
 void stopDriverService(){stopService(new Intent(this,DriverLocationService.class));}
 void stopOfferAlert(){Intent service=new Intent(this,DriverLocationService.class).setAction(DriverLocationService.ACTION_STOP_ALERT);if(Build.VERSION.SDK_INT>=26)startForegroundService(service);else startService(service);}
 void goOffline(){stopOfferAlert();stopDriverService();if(lm==null)lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{lm.removeUpdates(this);}catch(Exception ignored){}Location x=lastLocation;try{if(x==null&&checkSelfPermission(android.Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)x=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);}catch(Exception ignored){}if(x==null){long a=getSharedPreferences("avr",MODE_PRIVATE).getLong("last_lat",0),b=getSharedPreferences("avr",MODE_PRIVATE).getLong("last_lng",0);if(a!=0&&b!=0){x=new Location("saved");x.setLatitude(Double.longBitsToDouble(a));x.setLongitude(Double.longBitsToDouble(b));}}if(x==null){Toast.makeText(this,"Сначала дождитесь GPS",Toast.LENGTH_LONG).show();return;}sendLocation(x,false);}
 void sendLocation(Location l,boolean on){lastLocation=l;new Thread(()->{try{JSONObject r=ApiClient.post("/api/mobile_location.php",new JSONObject().put("lat",l.getLatitude()).put("lng",l.getLongitude()).put("online",on));runOnUiThread(()->{if(r.optBoolean("ok")){online=on;waitingForOnline=false;if(on)startDriverService();else stopDriverService();Toast.makeText(this,on?"Вы на линии":"Вы не на линии",Toast.LENGTH_SHORT).show();setupNav();linePage();}else Toast.makeText(this,r.optString("error","Ошибка GPS"),Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Нет связи с AV Rescue",Toast.LENGTH_LONG).show());}}).start();}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==90&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startLocationUpdates();}
 public void onLocationChanged(Location l){lastLocation=l;if(!executor)return;if(waitingForOnline){waitingForOnline=false;sendLocation(l,true);}else if(online)sendLocationSilent(l);}
 void sendLocationSilent(Location l){new Thread(()->{try{ApiClient.post("/api/mobile_location.php",new JSONObject().put("lat",l.getLatitude()).put("lng",l.getLongitude()).put("online",true));online=true;}catch(Exception ignored){}}).start();}
 public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}public void onStatusChanged(String p,int s,Bundle b){}
 void finance(){
  page("Доход и комиссия");JSONObject f=data.optJSONObject("finance"),ex=data.optJSONObject("executor");LinearLayout c=Ui.card(this);
  if(f==null){c.addView(Ui.muted(this,"Финансовых операций пока нет.",14));}
  else{
   double balance=f.optDouble("current_balance",ex==null?0:ex.optDouble("balance",0)),available=f.optDouble("available",Math.max(0,balance)),debt=f.optDouble("debt",Math.max(0,-balance));
   c.addView(Ui.text(this,"Доступно к выплате: "+Math.round(available)+" ₽",20,true));c.addView(Ui.text(this,"Текущий баланс: "+Math.round(balance)+" ₽",18,true));
   if(debt>0)c.addView(Ui.chip(this,"Задолженность AV Rescue: "+Math.round(debt)+" ₽",false));
   if(f.optDouble("requested",0)>0)c.addView(Ui.muted(this,"Ожидает выплаты: "+Math.round(f.optDouble("requested"))+" ₽",14));
   c.addView(Ui.muted(this,"Заказы: "+Math.round(f.optDouble("gross"))+" ₽",14));c.addView(Ui.muted(this,"Ваш заработок: "+Math.round(f.optDouble("earned"))+" ₽",14));c.addView(Ui.muted(this,"Комиссия AV Rescue: "+Math.round(f.optDouble("commission"))+" ₽",14));
  }
  if(ex!=null)c.addView(Ui.muted(this,"Текущая ставка комиссии: "+Math.round(ex.optDouble("commission_rate",20))+"%",14));content.addView(c);
  if(f!=null&&f.optDouble("available",0)>0){LinearLayout payout=Ui.card(this);payout.addView(Ui.text(this,"Заказать выплату",19,true));payout.addView(Ui.muted(this,"Укажите сумму и телефон СБП или реквизиты счёта.",13));EditText amount=Ui.input(this,"Сумма, ₽");amount.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText details=Ui.input(this,"Телефон СБП или реквизиты");payout.addView(amount);payout.addView(details);Button send=Ui.button(this,"Отправить заявку");send.setOnClickListener(v->requestPayout(amount,details,send));payout.addView(send);content.addView(payout);}
  if(f!=null){JSONArray payouts=f.optJSONArray("payouts");LinearLayout payoutHistory=Ui.card(this);payoutHistory.addView(Ui.text(this,"Выплаты",19,true));if(payouts==null||payouts.length()==0)payoutHistory.addView(Ui.muted(this,"Заявок на выплату пока нет.",14));else for(int i=0;i<payouts.length();i++){JSONObject x=payouts.optJSONObject(i);if(x==null)continue;payoutHistory.addView(Ui.text(this,x.optString("id","Выплата")+" • "+Math.round(x.optDouble("amount"))+" ₽",15,true));payoutHistory.addView(Ui.chip(this,payoutStatus(x.optString("status")),"paid".equals(x.optString("status"))));}content.addView(payoutHistory);}
  if(f!=null){JSONArray tx=f.optJSONArray("transactions");LinearLayout history=Ui.card(this);history.addView(Ui.text(this,"История по заказам",19,true));if(tx==null||tx.length()==0)history.addView(Ui.muted(this,"Операций пока нет.",14));else for(int i=0;i<tx.length();i++){JSONObject x=tx.optJSONObject(i);if(x==null)continue;boolean cash="cash".equals(x.optString("payment_method"));history.addView(Ui.text(this,x.optString("order_id","Заказ")+" • "+Math.round(x.optDouble("price"))+" ₽",16,true));history.addView(Ui.muted(this,(cash?"Наличные":"Оплата картой")+" • комиссия "+Math.round(x.optDouble("commission"))+" ₽",13));double change=x.optDouble("balance_change");history.addView(Ui.muted(this,(change>=0?"Зачислено: +":"Списано: ")+Math.round(Math.abs(change))+" ₽",13));}content.addView(history);}
 }
 void requestPayout(EditText amountField,EditText detailsField,Button button){double amount;try{amount=Double.parseDouble(amountField.getText().toString().trim().replace(',','.'));}catch(Exception e){Toast.makeText(this,"Укажите сумму выплаты",Toast.LENGTH_LONG).show();return;}String details=detailsField.getText().toString().trim();if(details.length()<4){Toast.makeText(this,"Укажите телефон СБП или реквизиты",Toast.LENGTH_LONG).show();return;}button.setEnabled(false);button.setText("Отправляем…");new Thread(()->{try{JSONObject r=ApiClient.post("/api/mobile_payout.php",new JSONObject().put("amount",amount).put("details",details));runOnUiThread(()->{if(r.optBoolean("ok")){Toast.makeText(this,"Заявка "+r.optString("payout_id")+" создана",Toast.LENGTH_LONG).show();refreshQuiet();}else{button.setEnabled(true);button.setText("Отправить заявку");Toast.makeText(this,r.optString("error","Заявка не создана"),Toast.LENGTH_LONG).show();}});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);button.setText("Отправить заявку");Toast.makeText(this,"Нет связи с AV Rescue",Toast.LENGTH_LONG).show();});}}).start();}
 String payoutStatus(String status){if("new".equals(status))return "● На рассмотрении";if("approved".equals(status))return "● Одобрена";if("paid".equals(status))return "● Выплачена";if("rejected".equals(status))return "● Отклонена";return "● "+status;}
 void more(){page("Ещё");if(staff()){quick("Заявки на регистрацию","Анкеты, фото, ВУ, СТС",()->applications());if(admin()){quick("Пользователи / клиенты","Просмотр, блокировка и удаление",()->resources("users","Пользователи / клиенты"));quick("B2B-партнёры","Корпоративные аккаунты",()->resources("b2b","B2B-партнёры"));quick("Сотрудники","Администраторы и диспетчеры",()->resources("staff","Сотрудники"));}quick("Тарифы и финансы","Комиссии, цены, выплаты",()->section("Тарифы и финансы","Управление тарифами подключено к общей серверной модели."));}else if(executor){quick("Профиль исполнителя","Редактировать данные, автомобиль, фото, ВУ и СТС",()->startActivity(new Intent(this,ExecutorProfileActivity.class)));quick("Выполняемые услуги","Выберите категории заказов",()->servicesPage());quick("Поддержка","8-925-584-58-58",()->{});}else quick("Профиль клиента","История и данные аккаунта",()->{});Button out=Ui.darkButton(this,"Выйти из аккаунта");out.setOnClickListener(v->logout());content.addView(out);}
 void applications(){page("Заявки на регистрацию");new Thread(()->{try{JSONObject r=ApiClient.get("/api/mobile_registration_admin.php");runOnUiThread(()->renderApplications(r));}catch(Exception e){runOnUiThread(()->error("Нет связи с сервером"));}}).start();}
 void renderApplications(JSONObject response){page("Заявки на регистрацию");if(!response.optBoolean("ok")){error(response.optString("error","Не удалось загрузить анкеты"));return;}JSONArray applications=response.optJSONArray("applications");if(applications==null||applications.length()==0){content.addView(Ui.muted(this,"Заявок пока нет.",14));return;}for(int i=0;i<applications.length();i++){JSONObject application=applications.optJSONObject(i);if(application==null)continue;LinearLayout card=Ui.card(this);String id=application.optString("id");String status=application.optString("status","review");boolean approved="approved".equals(status)||"auto_approved".equals(status);card.addView(Ui.text(this,application.optString("name","Исполнитель"),18,true));card.addView(Ui.chip(this,approved?"● ДОСТУП ОТКРЫТ":"● ОЖИДАЕТ МОДЕРАЦИИ",approved));card.addView(Ui.muted(this,"Телефон: "+application.optString("phone","—")+"\nEmail: "+application.optString("email","—"),14));card.addView(Ui.muted(this,"Техника: "+application.optString("vehicle_type","—")+"\nГосномер: "+application.optString("plate","—")+"\nУслуги: "+application.optJSONArray("services"),13));JSONObject documents=application.optJSONObject("documents");String[] kinds={"profile_photo","vehicle_front","vehicle_rear","vehicle_left","vehicle_right","driver_license_front","driver_license_back","sts_front","sts_back"};String[] labels={"Фото водителя / селфи","Авто — спереди","Авто — сзади","Авто — левый борт","Авто — правый борт","Водительское — лицевая сторона","Водительское — оборот","СТС — лицевая сторона","СТС — оборот"};for(int d=0;d<kinds.length;d++){String kind=kinds[d],label=labels[d];if(documents==null||documents.optString(kind,"").isEmpty()){card.addView(Ui.muted(this,label+": не загружено",12));continue;}ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setVisibility(View.GONE);Button show=Ui.darkButton(this,"Показать: "+label);show.setOnClickListener(v->loadModerationPhoto(id,kind,image,show));card.addView(show);card.addView(image);}if(!approved){Button approve=Ui.button(this,"Подтвердить регистрацию");approve.setOnClickListener(v->approveApplication(id,application.optString("name","исполнитель")));card.addView(approve);}content.addView(card);}}
 void loadModerationPhoto(String workerId,String kind,ImageView image,Button button){button.setEnabled(false);button.setText("Загружаем фотографию…");new Thread(()->{try{byte[] bytes=ApiClient.getBytes("/api/mobile_worker_document.php?worker_id="+Uri.encode(workerId)+"&kind="+Uri.encode(kind));Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length);runOnUiThread(()->{if(bitmap==null){button.setText("Не удалось открыть фотографию");return;}image.setImageBitmap(bitmap);image.setVisibility(View.VISIBLE);button.setText("Фотография загружена");});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);button.setText("Повторить загрузку фотографии");Toast.makeText(this,"Не удалось загрузить файл",Toast.LENGTH_LONG).show();});}}).start();}
 void approveApplication(String id,String name){new AlertDialog.Builder(this).setTitle("Подтвердить исполнителя?").setMessage("Подтвердите, что проверили данные, фотографию водителя, автомобиль, водительское удостоверение и СТС. После этого "+name+" сразу получит доступ к заявкам.").setNegativeButton("Отмена",null).setPositiveButton("Подтвердить",(dialog,which)->new Thread(()->{try{JSONObject result=ApiClient.post("/api/mobile_registration_admin.php",new JSONObject().put("action","approve_executor").put("id",id));runOnUiThread(()->{Toast.makeText(this,result.optBoolean("ok")?"Регистрация подтверждена":result.optString("error","Не удалось подтвердить"),Toast.LENGTH_LONG).show();if(result.optBoolean("ok"))applications();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Нет связи с сервером",Toast.LENGTH_LONG).show());}}).start()).show();}
 void applicationsLegacy(){page("Заявки на регистрацию");new Thread(()->{try{JSONObject r=ApiClient.get("/api/mobile_registration_admin.php");runOnUiThread(()->{page("Заявки на регистрацию");JSONArray a=r.optJSONArray("applications");if(a==null||a.length()==0){content.addView(Ui.muted(this,"Заявок пока нет.",14));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=Ui.card(this);c.addView(Ui.text(this,x.optString("name","Исполнитель"),17,true));c.addView(Ui.muted(this,x.optString("vehicle_type")+" • "+x.optString("plate"),13));c.addView(Ui.chip(this,x.optString("status","auto_approved"),true));c.addView(Ui.muted(this,"Администратор может провести выборочную проверку документов.",12));content.addView(c);}});}catch(Exception e){runOnUiThread(()->error("Нет связи с сервером"));}}).start();}
 void resources(String key,String title){page(title);new Thread(()->{try{JSONObject r=ApiClient.get("/api/mobile_resources.php");runOnUiThread(()->resourceRender(r,key,title));}catch(Exception e){runOnUiThread(()->error("Нет связи с сервером"));}}).start();}
 void resourceRender(JSONObject r,String key,String title){page(title);JSONArray a=r.optJSONArray(key);if(a==null||a.length()==0){content.addView(Ui.muted(this,"Данных пока нет.",14));return;}for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);LinearLayout c=Ui.card(this);if("workers".equals(key)){c.addView(Ui.text(this,x.optString("name","Исполнитель"),17,true));c.addView(Ui.chip(this,"● "+x.optString("status","offline"),x.optBoolean("online")));c.addView(Ui.muted(this,"Рейтинг "+x.optDouble("rating",5)+" • "+x.optString("phone"),13));}else if("fleet".equals(key)){c.addView(Ui.text(this,(x.optString("brand")+" "+x.optString("model")).trim(),17,true));c.addView(Ui.muted(this,x.optString("plate")+" • "+x.optString("status"),13));}else{c.addView(Ui.text(this,x.optString("name",x.optString("company",x.optString("login",title))),17,true));c.addView(Ui.muted(this,x.optString("phone",x.optString("email",x.optString("role",""))),13));if("users".equals(key)&&admin()){String uid=x.optString("id");Button del=Ui.darkButton(this,"Удалить аккаунт");del.setOnClickListener(v->confirmDelete(uid));c.addView(del);}}content.addView(c);}}
 void confirmDelete(String id){new AlertDialog.Builder(this).setTitle("Удалить аккаунт?").setMessage("Аккаунт будет удалён из базы пользователей. Действие требует подтверждения.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->new Thread(()->{try{JSONObject r=ApiClient.post("/api/mobile_user_admin.php",new JSONObject().put("action","delete").put("id",id));runOnUiThread(()->{Toast.makeText(this,r.optBoolean("ok")?"Аккаунт удалён":r.optString("error"),Toast.LENGTH_LONG).show();resources("users","Пользователи / клиенты");});}catch(Exception e){}}).start()).show();}
 void section(String t,String d){page(t);LinearLayout c=Ui.card(this);c.addView(Ui.muted(this,d,14));content.addView(c);}
 void servicesPage(){page("Выполняемые услуги");JSONObject ex=data.optJSONObject("executor");JSONArray current=ex==null?null:ex.optJSONArray("services");java.util.LinkedHashMap<String,CheckBox> checks=new java.util.LinkedHashMap<>();for(String service:new String[]{"Эвакуация","Техпомощь","Запуск двигателя","Замена колеса","Подвоз топлива","Вскрытие автомобиля"}){CheckBox check=new CheckBox(this);check.setText(service);check.setTextColor(Color.WHITE);boolean selected=false;if(current!=null)for(int i=0;i<current.length();i++)if(service.equals(current.optString(i)))selected=true;check.setChecked(selected);checks.put(service,check);content.addView(check);}Button save=Ui.button(this,"Сохранить услуги");save.setOnClickListener(v->{JSONArray selected=new JSONArray();for(java.util.Map.Entry<String,CheckBox> e:checks.entrySet())if(e.getValue().isChecked())selected.put(e.getKey());new Thread(()->{try{JSONObject r=ApiClient.post("/api/mobile_executor_services.php",new JSONObject().put("services",selected));runOnUiThread(()->{Toast.makeText(this,r.optBoolean("ok")?"Услуги сохранены":r.optString("error","Ошибка"),Toast.LENGTH_LONG).show();if(r.optBoolean("ok"))load();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Нет связи",Toast.LENGTH_LONG).show());}}).start();});content.addView(save);}
 void logout(){stopOfferAlert();stopDriverService();if(lm!=null)try{lm.removeUpdates(this);}catch(Exception ignored){}new Thread(()->{try{ApiClient.post("/api/mobile_logout.php",new JSONObject());}catch(Exception e){}runOnUiThread(()->{ApiClient.clear(this);startActivity(new Intent(this,LoginActivity.class));finish();});}).start();}
 String roleRu(String r){if("superadmin".equals(r))return "Главный администратор";if("admin".equals(r))return "Администратор";if("dispatcher".equals(r)||"staff".equals(r))return "Диспетчер";if("executor".equals(r))return "Исполнитель AV Rescue";if("b2b".equals(r))return "B2B-партнёр";return "Клиент AV Rescue";}
 String statusRu(String s){if("new".equals(s))return "Новая";if("searching".equals(s))return "Поиск водителя";if("offered".equals(s))return "Предложена";if("assigned".equals(s))return "Назначен водитель";if("enroute".equals(s))return "Еду к клиенту";if("arrived".equals(s))return "Прибыл";if("loading".equals(s))return "Погрузка";if("in_transit".equals(s))return "В пути с автомобилем";if("done".equals(s)||"completed".equals(s))return "Завершена";if("cancelled".equals(s))return "Отменена";return s;}
}
